src/Entity/Clientes.php
<?php

namespace App\Entity;

use App\Repository\ClientesRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ClientesRepository::class)]
class Clientes
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $first_name = null;

    #[ORM\Column(length: 255)]
    private ?string $last_name = null;

    #[ORM\Column(length: 11, unique: true)]
    private ?string $document_number = null;

    #[ORM\Column(length: 50, nullable: true)]
    private ?string $phone = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $address = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $updated_at = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $deleted_at = null;

    #[ORM\ManyToOne]
    private ?User $created_by = null;

    #[ORM\ManyToOne]
    private ?User $updated_by = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): static
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): static
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getDocumentNumber(): ?string
    {
        return $this->document_number;
    }

    public function setDocumentNumber(string $document_number): static
    {
        $this->document_number = $document_number;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(?string $phone): static
    {
        $this->phone = $phone;

        return $this;
    }

    public function getaddress(): ?string
    {
        return $this->address;
    }

    public function setaddress(?string $address): static
    {
        $this->address = $address;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeImmutable $updated_at): static
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getDeletedAt(): ?\DateTimeImmutable
    {
        return $this->deleted_at;
    }

    public function setDeletedAt(?\DateTimeImmutable $deleted_at): static
    {
        $this->deleted_at = $deleted_at;

        return $this;
    }

    public function getCreatedBy(): ?User
    {
        return $this->created_by;
    }

    public function setCreatedBy(?User $created_by): static
    {
        $this->created_by = $created_by;

        return $this;
    }

    public function getUpdatedBy(): ?User
    {
        return $this->updated_by;
    }

    public function setUpdatedBy(?User $updated_by): static
    {
        $this->updated_by = $updated_by;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\UniqueConstraint(name: 'UNIQ_IDENTIFIER_EMAIL', fields: ['email'])]
#[UniqueEntity(fields: ['email'], message: 'Ya existe un usuario con este email.')]
#[UniqueEntity(fields: ['dni'], message: 'Ya existe una cuenta con este DNI.')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180)]
    private ?string $email = null;

    /**
     * @var list<string> The user roles
     */
    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 255)]
    private ?string $complete_name = null;

    #[ORM\Column(length: 20, unique: true)]
    private ?string $dni = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->dni;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    /**
     * @param list<string> $roles
     */
    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Ensure the session doesn't contain actual password hashes by CRC32C-hashing them, as supported since Symfony 7.3.
     */
    public function __serialize(): array
    {
        $data = (array) $this;
        $data["\0".self::class."\0password"] = hash('crc32c', $this->password);

        return $data;
    }

    #[\Deprecated]
    public function eraseCredentials(): void
    {
        // @deprecated, to be removed when upgrading to Symfony 8
    }

    public function getCompleteName(): ?string
    {
        return $this->complete_name;
    }

    public function setCompleteName(string $complete_name): static
    {
        $this->complete_name = $complete_name;
        return $this;
    }

    public function getDni(): ?string
    {
        return $this->dni;
    }

    public function setDni(string $dni): static
    {
        $this->dni = $dni;
        return $this;
    }
}

src/Entity/Vehiculos.php
<?php

namespace App\Entity;

use App\Repository\VehiculosRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use App\Entity\Reservas;
use App\Entity\Proveedores;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

#[ORM\Entity(repositoryClass: VehiculosRepository::class)]
#[Vich\Uploadable]
class Vehiculos
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne]
    private ?Versiones $version = null;

    #[ORM\Column]
    private ?int $anio = null;

    #[ORM\Column(length: 100)]
    private ?string $chassis_number = null;

    #[ORM\Column(length: 100)]
    private ?string $engine_number = null;

    #[ORM\Column(length: 50)]
    private ?string $color = null;

    #[ORM\Column(type: Types::BIGINT, nullable: true)]
    private ?string $kilometers = null;

    #[ORM\Column(length: 50, nullable: true)]
    private ?string $state = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTime $entry_date = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 20, scale: 2, nullable: true)]
    private ?string $purchase_price = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 20, scale: 2, nullable: true)]
    private ?string $suggested_retail_price = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $internal_observations = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $updated_at = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $deleted_at = null;

    #[ORM\ManyToOne]
    private ?User $created_by = null;

    #[ORM\ManyToOne]
    private ?User $updated_by = null;

    /**
     * @var Collection<int, ImagenesVehiculos>
     */
    #[ORM\OneToMany(mappedBy: 'vehiculo', targetEntity: ImagenesVehiculos::class, cascade: ['persist', 'remove'], orphanRemoval: true)]
    private Collection $imagenesVehiculos;

    #[ORM\OneToOne(mappedBy: 'vehiculo', cascade: ['persist', 'remove'])]
    private ?Ventas $venta = null;

    #[ORM\OneToOne(mappedBy: 'vehiculo', cascade: ['persist', 'remove'])]
    private ?Reservas $reserva = null;

    public function __construct()
    {
        $this->imagenesVehiculos = new ArrayCollection();
    }

    #[ORM\Column(length: 20, nullable: true, unique: true)]
    private ?string $plateNumber = null;

    #[ORM\ManyToOne(inversedBy: 'vehiculosComprados')]
    #[ORM\JoinColumn(nullable: true)]
    private ?Proveedores $supplier = null;

    #[Vich\UploadableField(mapping: 'purchase_documents', fileNameProperty: 'purchaseDocumentName')]
    private ?File $purchaseDocumentFile = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $purchaseDocumentName = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 12, scale: 2, nullable: true)]
    private ?string $purchasePriceUsd = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 12, scale: 2, nullable: true)]
    private ?string $suggestedRetailPriceUsd = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getVersion(): ?Versiones
    {
        return $this->version;
    }

    public function setVersion(?Versiones $version): static
    {
        $this->version = $version;

        return $this;
    }

    public function getAnio(): ?int
    {
        return $this->anio;
    }

    public function setAnio(int $anio): static
    {
        $this->anio = $anio;

        return $this;
    }

    public function getChassisNumber(): ?string
    {
        return $this->chassis_number;
    }

    public function setChassisNumber(string $chassis_number): static
    {
        $this->chassis_number = $chassis_number;

        return $this;
    }

    public function getEngineNumber(): ?string
    {
        return $this->engine_number;
    }

    public function setEngineNumber(string $engine_number): static
    {
        $this->engine_number = $engine_number;

        return $this;
    }

    public function getColor(): ?string
    {
        return $this->color;
    }

    public function setColor(string $color): static
    {
        $this->color = $color;

        return $this;
    }

    public function getKilometers(): ?string
    {
        return $this->kilometers;
    }

    public function setKilometers(?string $kilometers): static
    {
        $this->kilometers = $kilometers;

        return $this;
    }

    public function getState(): ?string
    {
        return $this->state;
    }

    public function setState(?string $state): static
    {
        $this->state = $state;

        return $this;
    }

    public function getEntryDate(): ?\DateTime
    {
        return $this->entry_date;
    }

    public function setEntryDate(?\DateTime $entry_date): static
    {
        $this->entry_date = $entry_date;

        return $this;
    }

    public function getPurchasePrice(): ?string
    {
        return $this->purchase_price;
    }

    public function setPurchasePrice(?string $purchase_price): static
    {
        $this->purchase_price = $purchase_price;

        return $this;
    }

    public function getSuggestedRetailPrice(): ?string
    {
        return $this->suggested_retail_price;
    }

    public function setSuggestedRetailPrice(?string $suggested_retail_price): static
    {
        $this->suggested_retail_price = $suggested_retail_price;

        return $this;
    }

    public function getInternalObservations(): ?string
    {
        return $this->internal_observations;
    }

    public function setInternalObservations(string $internal_observations): static
    {
        $this->internal_observations = $internal_observations;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeImmutable $updated_at): static
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getDeletedAt(): ?\DateTimeImmutable
    {
        return $this->deleted_at;
    }

    public function setDeletedAt(?\DateTimeImmutable $deleted_at): static
    {
        $this->deleted_at = $deleted_at;

        return $this;
    }

    public function getCreatedBy(): ?User
    {
        return $this->created_by;
    }

    public function setCreatedBy(?User $created_by): static
    {
        $this->created_by = $created_by;

        return $this;
    }

    public function getUpdatedBy(): ?User
    {
        return $this->updated_by;
    }

    public function setUpdatedBy(?User $updated_by): static
    {
        $this->updated_by = $updated_by;

        return $this;
    }

    /**
     * @return Collection<int, ImagenesVehiculos>
     */
    public function getImagenesVehiculos(): Collection
    {
        return $this->imagenesVehiculos;
    }

    public function addImagenesVehiculo(ImagenesVehiculos $imagenesVehiculo): static
    {
        if (!$this->imagenesVehiculos->contains($imagenesVehiculo)) {
            $this->imagenesVehiculos->add($imagenesVehiculo);
            $imagenesVehiculo->setVehiculo($this);
        }

        return $this;
    }

    public function removeImagenesVehiculo(ImagenesVehiculos $imagenesVehiculo): static
    {
        if ($this->imagenesVehiculos->removeElement($imagenesVehiculo)) {
            // set the owning side to null (unless already changed)
            if ($imagenesVehiculo->getVehiculo() === $this) {
                $imagenesVehiculo->setVehiculo(null);
            }

            $this->setUpdatedAt(new \DateTimeImmutable());
        }

        return $this;
    }

    public function getVenta(): ?Ventas
    {
        return $this->venta;
    }

    public function setVenta(Ventas $venta): static
    {
        // set the owning side of the relation if necessary
        if ($venta->getVehiculo() !== $this) {
            $venta->setVehiculo($this);
        }

        $this->venta = $venta;

        return $this;
    }

    public function getReserva(): ?Reservas
    {
        return $this->reserva;
    }

    public function setReserva(Reservas $reserva): static
    {
        if ($reserva->getVehiculo() !== $this) {
            $reserva->setVehiculo($this);
        }
        $this->reserva = $reserva;
        return $this;
    }
    
    public function getPlateNumber(): ?string
    {
        return $this->plateNumber;
    }

    public function setPlateNumber(?string $plateNumber): static
    {
        $this->plateNumber = $plateNumber;

        return $this;
    }

    public function getSupplier(): ?Proveedores
    {
        return $this->supplier;
    }

    public function setSupplier(?Proveedores $supplier): static
    {
        $this->supplier = $supplier;

        return $this;
    }

    public function setPurchaseDocumentFile(?File $purchaseDocumentFile = null): void
    {
        $this->purchaseDocumentFile = $purchaseDocumentFile;
        if (null !== $purchaseDocumentFile) {
            // Es necesario para que el bundle sepa que hubo un cambio
            $this->setUpdatedAt(new \DateTimeImmutable());
        }
    }

    public function getPurchaseDocumentFile(): ?File
    {
        return $this->purchaseDocumentFile;
    }

    public function setPurchaseDocumentName(?string $purchaseDocumentName): void
    {
        $this->purchaseDocumentName = $purchaseDocumentName;
    }

    public function getPurchaseDocumentName(): ?string
    {
        return $this->purchaseDocumentName;
    }

    public function getPurchasePriceUsd(): ?string
    {

templates/vehiculos/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Detalle: {{ vehiculo.version.modelo.marca.name }} {{ vehiculo.version.modelo.name }}{% endblock %}

{% block body %}
<div class="page-header">
    <h3 class="fw-bold mb-3">Detalle del Vehículo</h3>
    <ul class="breadcrumbs">
        <li class="nav-home"><a href="{{ path('app_home') }}"><i class="icon-home"></i></a></li>
        <li class="separator"><i class="icon-arrow-right"></i></li>
        <li class="nav-item"><a href="{{ path('app_vehiculos_index') }}">Vehículos</a></li>
        <li class="separator"><i class="icon-arrow-right"></i></li>
        <li class="nav-item"><a href="#">ID #{{ vehiculo.id }}</a></li>
    </ul>
</div>

<div class="row">
    {# --- COLUMNA IZQUIERDA: CARRUSEL Y PESTAÑAS --- #}
    <div class="col-md-7">
        <div class="card">
            <div class="card-body">
                {% if vehiculo.imagenesVehiculos is not empty %}
                    <div id="vehicleCarousel" class="carousel slide" data-bs-ride="carousel">
                        <div class="carousel-inner">
                            {% for imagen in vehiculo.imagenesVehiculos %}
                                <div class="carousel-item {{ loop.first ? 'active' : '' }}">
                                    <img src="{{ vich_uploader_asset(imagen, 'imageFile') }}" class="d-block w-100 rounded" alt="Imagen {{ loop.index }}">
                                </div>
                            {% endfor %}
                        </div>
                        <button class="carousel-control-prev" type="button" data-bs-target="#vehicleCarousel" data-bs-slide="prev"><span class="carousel-control-prev-icon"></span></button>
                        <button class="carousel-control-next" type="button" data-bs-target="#vehicleCarousel" data-bs-slide="next"><span class="carousel-control-next-icon"></span></button>
                    </div>
                {% else %}
                    <div class="text-center p-5"><i class="fas fa-image fa-4x text-muted"></i><p class="mt-3">Este vehículo no tiene imágenes cargadas.</p></div>
                {% endif %}
            </div>
        </div>
        <div class="card">
            <div class="card-header">
                <ul class="nav nav-tabs card-header-tabs" id="myTab" role="tablist">
                    <li class="nav-item" role="presentation"><button class="nav-link active" id="caracteristicas-tab" data-bs-toggle="tab" data-bs-target="#caracteristicas" type="button" role="tab">Características</button></li>
                    <li class="nav-item" role="presentation"><button class="nav-link" id="observaciones-tab" data-bs-toggle="tab" data-bs-target="#observaciones" type="button" role="tab">Observaciones Internas</button></li>
                    <li class="nav-item" role="presentation"><button class="nav-link" id="historial-tab" data-bs-toggle="tab" data-bs-target="#historial" type="button" role="tab">Historial</button></li>
                </ul>
            </div>
            <div class="card-body">
                <div class="tab-content" id="myTabContent">
                    <div class="tab-pane fade show active" id="caracteristicas" role="tabpanel"><p>{{ vehiculo.version.characteristics|default('No hay características especificadas.')|nl2br }}</p></div>
                    <div class="tab-pane fade" id="observaciones" role="tabpanel"><p>{{ vehiculo.internalObservations|default('No hay observaciones internas.')|nl2br }}</p></div>
                    <div class="tab-pane fade" id="historial" role="tabpanel">
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item"><strong>Creado por:</strong> {{ vehiculo.createdBy.completeName|default('N/A') }} el {{ vehiculo.createdAt|date('d/m/Y H:i') }}</li>
                            <li class="list-group-item"><strong>Última modif.:</strong> {{ vehiculo.updatedBy.completeName|default('N/A') }} el {{ vehiculo.updatedAt|date('d/m/Y H:i') }}</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>

    {# --- COLUMNA DERECHA: DATOS DEL VEHÍCULO Y VENTA --- #}
    <div class="col-md-5">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">{{ vehiculo.version.modelo.marca.name }} {{ vehiculo.version.modelo.name }}</h4>
                <p class="card-category mb-0">{{ vehiculo.version.name }}</p>
            </div>
            <div class="card-body">
                <ul class="list-group list-group-flush">
                    <li class="list-group-item d-flex justify-content-between">
                        <span><strong>Precio Venta</strong> (sugerido):</span>
                        <span class="fw-bold fs-5 text-success">${{ vehiculo.suggestedRetailPrice|number_format(2, ',', '.') }}</span>
                    </li>
                    <li class="list-group-item d-flex justify-content-between">
                        <span><strong>Precio Compra</strong>:</span>
                        <span class="fw-bold fs-5 text-primary">${{ vehiculo.purchasePrice|number_format(2, ',', '.') }}</span>
                    </li>
                    <li class="list-group-item d-flex justify-content-between"><strong>Estado:</strong> <span class="badge bg-primary">{{ vehiculo.state }}</span></li>
                    <li class="list-group-item d-flex justify-content-between"><strong>Patente:</strong> <span>{{ vehiculo.plateNumber|default('N/A') }}</span></li>
                    <li class="list-group-item d-flex justify-content-between"><strong>Año:</strong> <span>{{ vehiculo.anio }}</span></li>
                    <li class="list-group-item d-flex justify-content-between"><strong>Color:</strong> <span>{{ vehiculo.color }}</span></li>
                    <li class="list-group-item d-flex justify-content-between"><strong>Kilometraje:</strong> <span>{{ vehiculo.kilometers|number_format(0, ',', '.') }} km</span></li>
					{% if vehiculo.purchaseDocumentName %}
						<li class="list-group-item">
							<strong>Boleto de Compra:</strong> 
							<a href="{{ vich_uploader_asset(vehiculo, 'purchaseDocumentFile') }}" target="_blank" class="btn btn-info btn-sm">
								<i class="fas fa-eye"></i> Ver Documento
							</a>
						</li>
					{% endif %}
				</ul>

                {% if vehiculo.venta %}
                    <hr>
                    <div class="d-flex justify-content-between align-items-center mt-3">
                        <h5 class="card-title mb-0">Información de la Venta</h5>
                        {% if vehiculo.venta.isPaymentOverdue() %}
                            <span class="badge bg-danger">En Deuda</span>
                        {% else %}
                            <span class="badge bg-success">Al día</span>
                        {% endif %}
                    </div>
                    <ul class="list-group list-group-flush mt-2">
                        <li class="list-group-item d-flex justify-content-between"><strong>Vendido a:</strong> <span>{{ vehiculo.venta.cliente.firstName }} {{ vehiculo.venta.cliente.lastName }}</span></li>
                        <li class="list-group-item d-flex justify-content-between"><strong>Fecha:</strong> <span>{{ vehiculo.venta.saleDate|date('d/m/Y') }}</span></li>
 
                        <li class="list-group-item d-flex justify-content-between"><strong>Precio Final:</strong> <span class="fw-bold text-success">${{ vehiculo.venta.finalSalePrice|number_format(2, ',', '.') }}</span></li>

                        <li class="list-group-item d-flex justify-content-between"><strong>Total Pagado:</strong> <span>${{ vehiculo.venta.getTotalPaid()|number_format(2, ',', '.') }}</span></li>
                        <li class="list-group-item d-flex justify-content-between"><strong>Saldo Pendiente:</strong> <span>${{ vehiculo.venta.getPendingBalance()|number_format(2, ',', '.') }}</span></li>
                    </ul>
                {% endif %}

                {% if vehiculo.supplier %}
                    <hr>
                    <div class="d-flex justify-content-between align-items-center mt-3">
                        <h5 class="card-title mb-0">Proveedor</h5>
                        <span class="badge bg-info">Registrado</span>
                    </div>
                    <ul class="list-group list-group-flush mt-2">
                        <li class="list-group-item d-flex justify-content-between"><strong>Nombre:</strong> <span>{{ vehiculo.supplier.name|default('N/A') }}</span></li>
                        <li class="list-group-item d-flex justify-content-between"><strong>Contacto:</strong> <span>{{ vehiculo.supplier.contactPerson|default('N/A') }}</span></li>
                        <li class="list-group-item d-flex justify-content-between"><strong>Teléfono:</strong> <span>{{ vehiculo.supplier.phone|default('N/A') }}</span></li>
                        <li class="list-group-item d-flex justify-content-between"><strong>Email:</strong> <span>{{ vehiculo.supplier.email|default('N/A') }}</span></li>
                        <li class="list-group-item d-flex justify-content-between"><strong>Dirección:</strong> <span>{{ vehiculo.supplier.address|default('N/A') }}</span></li>
                    </ul>
                {% endif %}
            </div>
            <div class="card-footer text-end">
                 <a href="{{ path('app_vehiculos_index') }}" class="btn btn-secondary">Volver al listado</a>
            </div>
        </div>
    </div>
</div>

{# --- NUEVA TABLA DE CUOTAS (SI EXISTE VENTA FINANCIADA) --- #}
{% if vehiculo.venta and vehiculo.venta.paymentMethod == 'Financiado' %}
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header"><h4 class="card-title">Plan de Pagos</h4></div>
            <div class="card-body">
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th># Cuota</th>
                            <th>Vencimiento</th>
                            <th>Monto Original</th>
                            <th>Monto Pagado</th>
                            <th>Moneda</th>
                            <th>Estado</th>
                            <th>Fecha de Pago</th>
                            <th class="text-end">Comprobante</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for cuota in vehiculo.venta.cuotas|sort((a, b) => a.installmentNumber <=> b.installmentNumber) %}
                        <tr class="{{ vehiculo.venta.isPaymentOverdue() and cuota.status == 'Pendiente' and cuota.dueDate < date('now') ? 'table-danger' : '' }}">
                            <td><strong>{{ cuota.installmentNumber }}</strong></td>
                            <td>{{ cuota.dueDate|date('d/m/Y') }}</td>
                            <td>${{ cuota.amount|number_format(2, ',', '.') }}</td>
                            <td>$ {{cuota.paidAmount ? cuota.paidAmount|number_format(2, ',', '.') : '0,00' }}</td>
                            <td>{{ cuota.paidCurrency ? cuota.paidCurrency : '-'}}</td>
                            <td>
                                {% if cuota.status == 'Pagada' %}
                                    <span class="badge bg-success">Pagada</span>
                                {% else %}
                                    <span class="badge bg-warning text-dark">Pendiente</span>
                                {% endif %}
                            </td>
                            <td>{{ cuota.paymentDate ? cuota.paymentDate|date('d/m/Y H:i') : 'N/A' }}</td>
                            <td class="text-end">
                                {% if cuota.receiptName %}
                                    <a href="{{ vich_uploader_asset(cuota, 'receiptFile') }}" target="_blank" class="btn btn-info btn-sm">
                                        <i class="fas fa-eye"></i> Ver
                                    </a>
                                {% else %}
                                    N/A
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endif %}
{% endblock %}